version: '3.8'

services:
  acudirtservice:
    image: acudirtservice:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - JWT_SECRET_KEY=MySecureJwtKey12345678901234567890

